extends: airbnb
env:
  browser: true
  node: true
rules:
  no-param-reassign:
    - error
    - { props: false }
  semi:
    - error
    - never
  no-console: off
  react/jsx-filename-extension: off
  react/prop-types: off
  jsx-a11y/href-no-hash: off
